[package]
name = "noir_verify_presentation"
type = "bin"
authors = [""]

[dependencies]
sha256 = { tag = "v0.1.4", git = "https://github.com/noir-lang/sha256" }
chacha_encoder = { tag = "v0.0.3", git = "https://github.com/piotr-stec/chacha-noir", directory = "chacha_encoder" }
