cert_commitment_data = [
    "2",
    "32",
    "135",
    "156",
    "156",
    "244",
    "36",
    "51",
    "250",
    "229",
    "84",
    "149",
    "64",
    "105",
    "124",
    "204",
    "21",
    "46",
    "100",
    "181",
    "108",
    "140",
    "104",
    "165",
    "234",
    "53",
    "179",
    "30",
    "80",
    "17",
    "122",
    "161",
    "30",
    "104",
]
commitment_root = [
    "101",
    "131",
    "100",
    "70",
    "239",
    "65",
    "183",
    "69",
    "95",
    "47",
    "52",
    "218",
    "246",
    "105",
    "200",
    "97",
    "192",
    "151",
    "187",
    "81",
    "149",
    "55",
    "194",
    "134",
    "22",
    "153",
    "122",
    "199",
    "64",
    "61",
    "77",
    "247",
]
connection_info_data = [
    "48",
    "84",
    "156",
    "104",
    "0",
    "0",
    "0",
    "0",
    "0",
    "156",
    "0",
    "0",
    "0",
    "188",
    "3",
    "0",
    "0",
]
header_root = [
    "37",
    "101",
    "46",
    "228",
    "121",
    "51",
    "29",
    "36",
    "105",
    "184",
    "74",
    "15",
    "57",
    "34",
    "250",
    "81",
    "143",
    "228",
    "152",
    "145",
    "181",
    "198",
    "37",
    "46",
    "153",
    "204",
    "241",
    "100",
    "243",
    "162",
    "115",
    "88",
]
key = [
    "58",
    "121",
    "229",
    "75",
    "155",
    "17",
    "179",
    "190",
    "18",
    "24",
    "145",
    "135",
    "147",
    "7",
    "245",
    "177",
    "251",
    "18",
    "23",
    "153",
    "77",
    "119",
    "113",
    "196",
    "162",
    "77",
    "169",
    "157",
    "116",
    "122",
    "81",
    "141",
    "56",
    "104",
    "189",
    "117",
    "83",
    "247",
    "215",
    "107",
    "231",
    "42",
    "183",
    "111",
    "160",
    "81",
    "134",
    "25",
    "140",
    "78",
    "31",
    "100",
    "63",
    "179",
    "235",
    "242",
    "72",
    "174",
    "23",
    "165",
    "213",
    "46",
    "227",
    "254",
]
message = [
    "213",
    "195",
    "119",
    "142",
    "42",
    "229",
    "138",
    "207",
    "50",
    "53",
    "10",
    "65",
    "49",
    "255",
    "59",
    "79",
    "0",
    "0",
    "0",
    "0",
    "2",
    "32",
    "37",
    "101",
    "46",
    "228",
    "121",
    "51",
    "29",
    "36",
    "105",
    "184",
    "74",
    "15",
    "57",
    "34",
    "250",
    "81",
    "143",
    "228",
    "152",
    "145",
    "181",
    "198",
    "37",
    "46",
    "153",
    "204",
    "241",
    "100",
    "243",
    "162",
    "115",
    "88",
]
server_ephemeral_key_data = [
    "0",
    "65",
    "4",
    "130",
    "89",
    "154",
    "155",
    "135",
    "76",
    "20",
    "70",
    "99",
    "195",
    "224",
    "45",
    "34",
    "161",
    "101",
    "201",
    "171",
    "250",
    "161",
    "145",
    "204",
    "8",
    "214",
    "69",
    "6",
    "247",
    "234",
    "124",
    "172",
    "87",
    "61",
    "1",
    "166",
    "20",
    "127",
    "135",
    "232",
    "208",
    "98",
    "69",
    "206",
    "218",
    "134",
    "92",
    "158",
    "172",
    "153",
    "74",
    "63",
    "115",
    "253",
    "188",
    "147",
    "155",
    "199",
    "52",
    "37",
    "114",
    "240",
    "108",
    "204",
    "56",
    "53",
    "83",
]
signature = [
    "236",
    "19",
    "141",
    "195",
    "185",
    "166",
    "248",
    "45",
    "81",
    "28",
    "180",
    "91",
    "32",
    "180",
    "171",
    "6",
    "113",
    "25",
    "181",
    "217",
    "48",
    "0",
    "219",
    "45",
    "148",
    "77",
    "187",
    "200",
    "68",
    "77",
    "207",
    "126",
    "11",
    "175",
    "124",
    "159",
    "135",
    "137",
    "143",
    "66",
    "74",
    "190",
    "220",
    "110",
    "184",
    "4",
    "43",
    "220",
    "209",
    "170",
    "224",
    "35",
    "93",
    "158",
    "143",
    "231",
    "23",
    "103",
    "71",
    "249",
    "235",
    "80",
    "132",
    "74",
]
transcript_commitments_data = [
    "0",
    "2",
    "32",
    "101",
    "131",
    "100",
    "70",
    "239",
    "65",
    "183",
    "69",
    "95",
    "47",
    "52",
    "218",
    "246",
    "105",
    "200",
    "97",
    "192",
    "151",
    "187",
    "81",
    "149",
    "55",
    "194",
    "134",
    "22",
    "153",
    "122",
    "199",
    "64",
    "61",
    "77",
    "247",
    "151",
    "218",
    "132",
    "14",
    "253",
    "196",
    "67",
    "180",
    "89",
    "146",
    "38",
    "92",
    "226",
    "68",
    "211",
    "175",
    "248",
    "200",
    "37",
    "12",
    "206",
    "221",
    "230",
    "61",
    "232",
    "40",
    "227",
    "204",
    "226",
    "74",
    "66",
    "100",
    "135",
    "132",
    "190",
    "99",
    "199",
    "145",
    "161",
    "36",
    "27",
    "112",
    "231",
    "40",
    "117",
    "76",
    "35",
    "102",
]
verifying_key_data = [
    "1",
    "33",
    "2",
    "58",
    "121",
    "229",
    "75",
    "155",
    "17",
    "179",
    "190",
    "18",
    "24",
    "145",
    "135",
    "147",
    "7",
    "245",
    "177",
    "251",
    "18",
    "23",
    "153",
    "77",
    "119",
    "113",
    "196",
    "162",
    "77",
    "169",
    "157",
    "116",
    "122",
    "81",
    "141",
]

[encoder_secret]
delta = [
    "135",
    "132",
    "190",
    "99",
    "199",
    "145",
    "161",
    "36",
    "27",
    "112",
    "231",
    "40",
    "117",
    "76",
    "35",
    "102",
]
seed = [
    "151",
    "218",
    "132",
    "14",
    "253",
    "196",
    "67",
    "180",
    "89",
    "146",
    "38",
    "92",
    "226",
    "68",
    "211",
    "175",
    "248",
    "200",
    "37",
    "12",
    "206",
    "221",
    "230",
    "61",
    "232",
    "40",
    "227",
    "204",
    "226",
    "74",
    "66",
    "100",
]

[transcript_close_time]
data = ["34", "99", "108", "111", "115", "101", "84", "105", "109", "101", "34", "58", "49", "55", "53", "53", "48", "55", "53", "54", "50", "56", "54", "54", "56"]
blinders = [
    "23",
    "54",
    "106",
    "75",
    "6",
    "96",
    "142",
    "209",
    "217",
    "251",
    "144",
    "62",
    "239",
    "135",
    "1",
    "97",
]
direction = "1"
position = "930"

[transcript_mins]
blinders = [
    "52",
    "71",
    "189",
    "178",
    "12",
    "218",
    "12",
    "125",
    "139",
    "191",
    "161",
    "105",
    "21",
    "235",
    "241",
    "34",
]
data = ["34", "109", "105", "110", "115", "34", "58", "53"]
direction = "1"
position = "900"

[transcript_price]
blinders = [
    "152",
    "125",
    "154",
    "112",
    "165",
    "175",
    "200",
    "210",
    "199",
    "114",
    "42",
    "164",
    "151",
    "44",
    "128",
    "112",
]
data = [
    "34",
    "112",
    "114",
    "105",
    "99",
    "101",
    "34",
    "58",
    "34",
    "51",
    "46",
    "54",
    "50",
    "53",
    "57",
    "54",
    "54",
    "54",
    "55",
    "34",
]
direction = "1"
position = "909"

[transcript_symbol]
blinders = [
    "98",
    "132",
    "183",
    "76",
    "52",
    "28",
    "186",
    "241",
    "156",
    "202",
    "53",
    "199",
    "55",
    "90",
    "4",
    "150",
]
data = [
    "115",
    "121",
    "109",
    "98",
    "111",
    "108",
    "61",
    "85",
    "83",
    "68",
    "84",
    "80",
    "76",
    "78",
]
direction = "0"
position = "44"
